version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: docker/app/local/Dockerfile
    volumes:
      - ../:/go/src/github.com/CA22-game-creators/cookingbomb-server
    restart: always
    tty: true
    ports:
      - "8080:8080"
