// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package account

import (
	"github.com/CA22-game-creators/cookingbomb-apiserver/application/account/signup"
	"github.com/CA22-game-creators/cookingbomb-apiserver/domain/model/user"
	"github.com/CA22-game-creators/cookingbomb-apiserver/infrastructure/mysql"
	user2 "github.com/CA22-game-creators/cookingbomb-apiserver/infrastructure/repository/user"
	account2 "github.com/CA22-game-creators/cookingbomb-apiserver/presentation/account"
	"github.com/CA22-game-creators/cookingbomb-apiserver/util"
	"github.com/CA22-game-creators/cookingbomb-proto/server/pb"
)

// Injectors from wire.go:

func DI() proto.AccountServicesServer {
	idGenerator := util.NewIDGenerator()
	tokenGenerator := util.NewTokenGenerator()
	cryptoManager := util.NewCryptManager()
	factory := user.NewFactory(idGenerator, tokenGenerator, cryptoManager)
	db := mysql.NewDB()
	repository := user2.NewRepository(db)
	inputPort := account.New(factory, repository)
	accountServicesServer := account2.New(inputPort)
	return accountServicesServer
}
