name: CD

on:
  push:
    branches:
      - main
env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  GOOGLE_PROJECT_NAME: ${{ secrets.GOOGLE_PROJECT_NAME }}
  APP_NAME: app

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --enable=gosec,prealloc,gocognit

      - name: Run test
        run: make test

      - name: GCP Authenticate
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT_NAME }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - name: Build a docker image
        run: docker build -t gcr.io/$GOOGLE_PROJECT_NAME/$APP_NAME:latest -f ./docker/app/prod/Dockerfile .

      - name: Push the docker image
        run: docker push gcr.io/$GOOGLE_PROJECT_NAME/$APP_NAME:latest


