name: CI

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - "**.md"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Go mod download
      run: go mod tidy

    - name: Run golangci-lint
      run: golangci-lint run --enable=gosec,prealloc,gocognit

    - name: Run test
      run: make test
